version: 1.1.3
primary: indigo
accent: pink
roboto: 1
remote: 1
headerFixed: 1
headerWaterfall: 1
headerScroll: 1
headerTransparent: 0
headerSeamed: 0
drawerFixed: 0
footer: mega
webAppManifest: 1
_core:
  default_config_hash: WkEcLJc9xLFExvfBvnZ6OqZSdAgPWJjlNH1D4r1ge3Q
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: profiles/lightning/lightning.png
favicon:
  use_default: 0
  path: profiles/lightning/favicon.ico
  mimetype: image/vnd.microsoft.icon
